services:
    nest-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        depends_on:
            - mysql-container
            - redis-container
        ports:
            - '3000:3000'
    mysql-container:
        image: mysql
        ports:
            - '3306:3306'
        volumes:
            - D:\docker-demo:/var/lib/mysql
        environment:
            MYSQL_DATABASE: aaa
            MYSQL_ROOT_PASSWORD: 123456
    redis-container:
        image: redis
        ports:
            - '6379:6379'
        volumes:
            - D:\docker-demo/redis:/data
