# services:
#     nest-app:
#         build:
#             context: ./
#             dockerfile: ./Dockerfile
#         depends_on:
#             - mysql-container
#             - redis-container
#         ports:
#             - '3000:3000'
#     mysql-container:
#         image: mysql
#         ports:
#             - '3306:3306'
#         volumes:
#             - D:\docker-demo:/var/lib/mysql
#         environment:
#             MYSQL_DATABASE: aaa
#             MYSQL_ROOT_PASSWORD: 123456
#     redis-container:
#         image: redis
#         ports:
#             - '6379:6379'
#         volumes:
#             - D:\docker-demo/redis:/data




# # version 是指定 docker-compose.yml 的版本，因为不同版本配置不同。
# version: '3.8'
# services:
#     nest-app:
#         build:
#             context: ./
#             dockerfile: ./Dockerfile
#         depends_on:
#             - mysql-container
#             - redis-container
#         ports:
#             - '3000:3000'
#         networks:
#             - common-network
#     mysql-container:
#         image: mysql
#         # ports:
#         #     - '3306:3306'
#         volumes:
#             - D:\docker-demo:/var/lib/mysql
#         environment:
#             MYSQL_DATABASE: aaa
#             MYSQL_ROOT_PASSWORD: 123456
#         networks:
#             - common-network
#     redis-container:
#         image: redis
#         # ports:
#         #     - '6379:6379'
#         volumes:
#             - D:\docker-demo/redis:/data
#         networks:
#             - common-network
# # 通过 networks 指定创建的 common-network 桥接网络，网络驱动程序指定为 bridge
# networks:
#     common-network:
#         driver: bridge





# 不过，其实不指定 networks 也可以，docker-compose 会创建个默认的。
# version 是指定 docker-compose.yml 的版本，因为不同版本配置不同。
version: '4.8'
services:
    nest-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        depends_on:
            - mysql-container
            - redis-container
        ports:
            - '3000:3000'
        # networks:
        #     - common-network
    mysql-container:
        image: mysql
        volumes:
            - D:\docker-demo:/var/lib/mysql
        environment:
            MYSQL_DATABASE: aaa
            MYSQL_ROOT_PASSWORD: 123456
        # networks:
        #     - common-network
    redis-container:
        image: redis
        volumes:
            - D:\docker-demo/redis:/data
        # networks:
        #     - common-network
# 通过 networks 指定创建的 common-network 桥接网络，网络驱动程序指定为 bridge
# networks:
#     common-network:
#         driver: bridge
