version: '3.8'
services:
    # fe-app:
    #     # image: fe-container:first
    #     # 阿里云镜像
    #     image: registry.cn-qingdao.aliyuncs.com/阿里云镜像-命名空间/阿里云镜像-仓库名称:阿里云镜像-版本号
    #     ports:
    #     - 80:80
    #     depends_on:
    #     - nest-app
    #     networks:
    #     - common-network
    nest-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        depends_on:
            - mysql-container
            - redis-container
        ports:
            - 3005:3005
        restart: always
        networks:
            - common-network
    mysql-container:
        image: mysql
        volumes:
            # mac
            - /Users/guang/mysql-data:/var/lib/mysql
            # windows 适合本地开发是windows电脑
            # - D:\\docker-demo:/var/lib/mysql
        environment:
            MYSQL_DATABASE: meeting_room_booking_system
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_HOST: "%"
        # command: --bind-address=0.0.0.0
        # 设置默认字符集
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci 
        restart: always
        networks:
            - common-network
    redis-container:
        image: redis
        volumes:
            # mac
            - /Users/guang/redis-data:/data
            # windows 适合本地开发是windows电脑
            # - D:\\docker-demo\\redis:/data
        restart: always
        networks:
            - common-network
    minio-container:
        image: bitnami/minio:latest
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - /Users/guang/minio:/bitnami/minio/data
        environment:
            MINIO_ROOT_USER: guang
            MINIO_ROOT_PASSWORD: dongdong
        restart: always
        networks:
            - common-network
networks:
    common-network:
        driver: bridge
